### ISSUE TITLE
Сборка

### ISSUE THREAD

**Issue by sodiqit** [staya-bomjei/range-slider#13]
Не собирается проект
![image](https://user-images.githubusercontent.com/47000555/161422278-5d2e50ea-d0fa-42f6-804e-56df64d258cd.png)

**Comment by staya-bomjei** [comment]
Какая у тебя операционная система?
P.S. У меня собирается клон с гита.
![image](https://user-images.githubusercontent.com/56907669/161422931-4499070f-aaa5-49d3-98da-4c1bf202b073.png)

**Comment by sodiqit** [comment]
ubuntu

**Comment by staya-bomjei** [comment]
Попробуй обновить свой Node, я использую 16.13.1.

**Comment by sodiqit** [comment]
Угу, на 16.13.1 собрался
