### ISSUE TITLE
Возвращаемое значение getOptions

### ISSUE THREAD

**Issue by sodiqit** [staya-bomjei/range-slider#14]
почему просто не возвращать `this.options`?
![image](https://user-images.githubusercontent.com/47000555/161422554-a035b410-c86b-45f8-b80f-3c9449e9bf57.png)

**Comment by staya-bomjei** [comment]
Поэтому что это делает возможным неявное изменение опций в обход метода setOptions, который может вызывать дополнительные методы для достижения разных эффектов (например, изменение View).

**Comment by sodiqit** [comment]
Тогда для таких случаев лучше применять глубокое копирование, потому что таким образом копируются только примитивы. Да, у тебя большинство примитивов, но также есть массив со строками. В этом случае он не скопирует массив, а скопирует ссылку на него. 

Изменять ничего не нужно, просто на будущее
