### ISSUE TITLE
статичные методы

### ISSUE THREAD

**Issue by sodiqit** [staya-bomjei/range-slider#15]
зачем делать `checkStrings` статичным методом? если он используется только в самой модели на уровне объекта?
![image](https://user-images.githubusercontent.com/47000555/161422740-e92a5283-ad7a-4145-86eb-170fb7299725.png)
Аналогично с `checkOptions`
![image](https://user-images.githubusercontent.com/47000555/161422767-34480a05-3fe4-4ea5-a370-1f96ac9f6f43.png)

Это больше подходит к приватным методам

**Comment by staya-bomjei** [comment]
Дело в том, что эти статичные методы не используют 'this', поэтому я не сделал их приватными. А если сделать приватными то линтер будет ругаться.

**Comment by sodiqit** [comment]
А, хорошо, но как по мне лучше такие функции выносить в utils модели. Но пусть останется так тогда
