### ISSUE TITLE
Кликабельные элементы

### ISSUE THREAD

**Issue by sodiqit** [staya-bomjei/range-slider#16]
поставь кликабельным элементам `cursor: pointer`

**Comment by staya-bomjei** [comment]
Честно говоря, я не нашел кликабельных элементов, у которых не задано свойство `cursor` (у ползунков и подсказок стоит `cursor: grab`, потому что это не кликабельные элементы, а перетаскиваемые), кроме стрелочек у input. 
![image](https://user-images.githubusercontent.com/56907669/161509913-e1dc1e51-1dcd-4903-83b4-5bf61ef61468.png)
Я добавил решение, которое работает на нескольких браузерах, но не работает в Firefox.
