### ISSUE TITLE
Наслоение

### ISSUE THREAD

**Issue by sodiqit** [staya-bomjei/range-slider#17]
шаг 33
![image](https://user-images.githubusercontent.com/47000555/161423829-dcd3ddc7-15e7-4ef7-8899-0fd5cc5480b1.png)

**Comment by staya-bomjei** [comment]
Я не знаю решения для этого случая. Можно, конечно, ограничить количество частей, чтобы не наслаивались, но если сам по себе слайдер будет узким, то наслоение случится даже с двумя метками.

**Comment by staya-bomjei** [comment]
Моё решение не решает проблему наслоения при изменении размеров самого slider, т.к. я не предполагал такого поведения изначально, но можно будет добавить, если это необходимо.
